import react from "react";
import "./table.scss";
const Table = () => {
  return (
    <>
      <div className={"global__container"}>
        <table>
          <caption>Статистика атак</caption>
          <thead>
            <tr>
              <th>№</th>
              <th>Время</th>
              <th>Тип начала</th>
              <th>Владение</th>
              <th>На площадке</th>
              <th>Тип времени</th>
              <th>Время</th>
              <th>Тип атаки</th>
              <th>Способ</th>
              <th>Зона</th>
              <th>Ассист</th>
              <th>Фол</th>
              <th>Забитые</th>
              <th>Потеря</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>1</td>
              <td>5</td>
              <td>4444</td>
              <td></td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
            </tr>
            <tr>
              <td>1</td>
              <td>1</td>
              <td>5</td>
              <td>4444</td>
              <td></td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
            </tr>
            <tr>
              <td>1</td>
              <td>1</td>
              <td>5</td>
              <td></td>
              <td></td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
            </tr>
            <tr>
              <td>1</td>
              <td>1</td>
              <td>5</td>
              <td></td>
              <td></td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
            </tr>
            <tr>
              <td>1</td>
              <td>1</td>
              <td>5</td>
              <td></td>
              <td></td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
            </tr>
            <tr>
              <td>1</td>
              <td>1</td>
              <td>5</td>
              <td></td>
              <td></td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
              <td>4</td>
            </tr>
          </tbody>
        </table>
      </div>
    </>
  );
};

export default Table;
